### ISSUE TITLE
Snapshots are not showing up in grub

### ISSUE THREAD

**Issue by atiredman** [Antynea/grub-btrfs#111]
Hi,
I installed grub-btrfs and had it working briefly, however the option to boot into the snapshots stopped showing up in grub for some reason.
When I run grub-mkconfig -o /boot/grub/grub.cfg, I get the output below.
```
 
> Generating grub configuration file ...
> Found linux image: /boot/vmlinuz-linux
> Found initrd image: /boot/intel-ucode.img /boot/initramfs-linux.img
> Found fallback initrd image(s) in /boot: initramfs-linux-fallback.img
> Found Windows Boot Manager on /dev/nvme0n1p1@/EFI/Microsoft/Boot/bootmgfw.efi
> Detecting snapshots ...
> Info: Separate boot partition not detected 
> Found snapshot: 2020-10-04 10:02:38 | timeshift-btrfs/snapshots/2020-10-04_10-02-38/@
> Found snapshot: 2020-10-04 10:00:01 | timeshift-btrfs/snapshots/2020-10-04_10-00-01/@
> Found snapshot: 2020-10-03 22:13:09 | timeshift-btrfs/snapshots/2020-10-03_22-13-09/@
> Found snapshot: 2020-10-03 12:44:02 | timeshift-btrfs/snapshots/2020-10-03_12-44-01/@
> Found snapshot: 2020-10-03 12:00:01 | timeshift-btrfs/snapshots/2020-10-03_12-00-01/@
> Found snapshot: 2020-10-02 15:38:00 | timeshift-btrfs/snapshots/2020-10-04_11-28-44/@
> Found 6 snapshot(s)
> Found Windows Boot Manager on /dev/nvme0n1p1@/EFI/Microsoft/Boot/bootmgfw.efi
> Detecting snapshots ...
> Info: Separate boot partition not detected 
> Found snapshot: 2020-10-04 10:02:38 | timeshift-btrfs/snapshots/2020-10-04_10-02-38/@
> Found snapshot: 2020-10-04 10:00:01 | timeshift-btrfs/snapshots/2020-10-04_10-00-01/@
> Found snapshot: 2020-10-03 22:13:09 | timeshift-btrfs/snapshots/2020-10-03_22-13-09/@
> Found snapshot: 2020-10-03 12:44:02 | timeshift-btrfs/snapshots/2020-10-03_12-44-01/@
> Found snapshot: 2020-10-03 12:00:01 | timeshift-btrfs/snapshots/2020-10-03_12-00-01/@
> Found snapshot: 2020-10-02 15:38:00 | timeshift-btrfs/snapshots/2020-10-04_11-28-44/@
> Found 6 snapshot(s)
> done

```

Grub presents me with 2 boot options 
Arch Linux & Windows 10, I'd like to restore the option to boot into Arch Linux snapshots if possible

These are the related packages on my system:
grub 2:2.04-8
grub-btrfs 4.6-1
timeshift 20.03-1
timeshift-autosnap 0.9-1

I'm also curious why my snapshots are showing up multiple times when I run grub-mkconfig -o /boot/grub/grub.cfg if you have any idea.

Thanks in advance!

**Comment by Antynea** [comment]
hello,
Some things are not working correctly in your setup.
Uninstalled grub-btrfs via `pacman -R grub-btrfs`.

Then make sure that :
/etc/grub.d doesn't content 41_snapshots or similar.
/etc/default/ doesn't content grub-btrfs or similar.
/boot/grub/ doesn't content grub-btrfs.cfg or similar.
If necessary, delete them.

Perform grub-mkconfig again
and check if "Detecting snapshots ..." has disappeared.
Which should be the case. Otherwise, a problem persists.

If everything is ok, install grub-btrfs via `pacman -S grub-btrfs`.
Perform grub-mkconfig again,
and check if "Detecting snapshots ..." has appeared.

At this point, don't enable `grub-btrfs.path`.

hoping we can help you...
