### ISSUE TITLE
OverlayFS does not work with Snapper Rollback

### ISSUE THREAD

**Issue by tommytran732** [Antynea/grub-btrfs#159]
Hi, 

I am running into a tiny issue and I hope you could help me. Using the OverlayFS does help with the problem that certain directories in /var should be writable (so I don't have to create some new BTRFS subvols for them), but then the system is no longer recognized as BTRFS, and thus `snapper rollback` does not work from inside of the snapshot.

On openSUSE, the user is able to boot into a read only snapshot, verify that everything works, then do a `snapper rollback` while they are inside of that snapshot. openSUSE can do this because the entire @/var subvolume is writable and isn't rolled back with the rest of the system, but this isn't ideal for an Arch system because the pacman database and other stuff are in there.

I wonder if there are any workarounds for this problem with OverlayFS. It would be nice not having to creates subvolumes for those directories which needs to be writable :(

Thank you,
Tom

**Comment by Antynea** [comment]
Hello,

Indeed when you boot with overlayfs, the system behaves like a `live Arch Linux USB/CD`.

The snapper commands aren't available, because the `fstype `isn't `btrfs`.

`--root` option of snapper command doesn't work apparently ...

So you have to do it yourself.
You can help yourself with [this wiki section](https://wiki.archlinux.org/title/Snapper#Restoring_/_to_its_previous_snapshot) which is based on [this layout](https://wiki.archlinux.org/title/Snapper#Suggested_filesystem_layout).

I haven't tried [rollback-git](https://aur.archlinux.org/packages/rollback-git/) but it should work.

I don't know your exact layout, but the information provided should help you.
Good luck 👍

**Comment by tommytran732** [comment]
> Hello,
> 
> Indeed when you boot with overlayfs, the system behaves like a `live Arch Linux USB/CD`.
> 
> The snapper commands aren't available, because the `fstype `isn't `btrfs`.
> 
> `--root` option of snapper command doesn't work apparently ...
> 
> So you have to do it yourself.
> You can help yourself with [this wiki section](https://wiki.archlinux.org/title/Snapper#Restoring_/_to_its_previous_snapshot) which is based on [this layout](https://wiki.archlinux.org/title/Snapper#Suggested_filesystem_layout).
> 
> I haven't tried [rollback-git](https://aur.archlinux.org/packages/rollback-git/) but it should work.
> 
> I don't know your exact layout, but the information provided should help you.
> Good luck 👍

Hi,

Thank you for your help. It's unfortunate that there is no work around for this :(
As for the setup on the wiki, I did try it out, but it is more for timeshift in my opinion, snapper expects SUSE like layouts. :P
I guess I will just go back to creating the subvolumes for /var/lib/gdm and /var/lib/AccountServices and replicate openSUSE's behavior 👍

Also just in case anyone reading this is curious, this is my current layout:

<img width="818" alt="Screen Shot 2021-07-08 at 2 56 15 PM" src="https://user-images.githubusercontent.com/57488583/124976015-b799e180-dffc-11eb-9f8e-7c70ecb94bda.png">
