### ISSUE TITLE
Is this supposed to work on non UEFI installations?

### ISSUE THREAD

**Issue by masavini** [Antynea/grub-btrfs#182]
Hi,
I hope this question is not too silly, but I really couldn't find this info anywhere...

I tried to install grub-btrfs on a bios grub installation, but with no success...
This is `systemctl status grub-btrfs.service` output:
```
● grub-btrfs.service - Regenerate grub-btrfs.cfg
     Loaded: loaded (/lib/systemd/system/grub-btrfs.service; bad; vendor preset: enabled)
     Active: inactive (dead) since Thu 2021-11-11 00:09:27 CET; 8min ago
TriggeredBy: ● grub-btrfs.path
    Process: 1681 ExecStart=/usr/bin/bash -c if [ -s "${GRUB_BTRFS_GRUB_DIRNAME:-/boot/grub}/grub-btrfs.cfg" ]; then /etc/grub.d/41_snapshots-btrfs; else ${GRUB_BTRFS_MKCONFIG:-grub-mkconfig} -o ${GRUB_BTRFS_GRUB_DIRNAM>
   Main PID: 1681 (code=exited, status=0/SUCCESS)

Nov 11 00:09:26 stamina 05efi[2470]: debug: Not on UEFI platform
Nov 11 00:09:26 stamina os-prober[2471]: debug: running /usr/lib/os-probes/mounted/10freedos on mounted /dev/sda3
Nov 11 00:09:26 stamina 10freedos[2473]: debug: /dev/sda3 is not a FAT partition: exiting
Nov 11 00:09:27 stamina os-prober[2477]: debug: running /usr/lib/os-probes/mounted/20macosx on mounted /dev/sda3
Nov 11 00:09:27 stamina os-prober[2486]: debug: running /usr/lib/os-probes/mounted/40lsb on mounted /dev/sda3
Nov 11 00:09:27 stamina os-prober[2490]: debug: running /usr/lib/os-probes/mounted/80minix on mounted /dev/sda3
Nov 11 00:09:27 stamina os-prober[2499]: debug: running /usr/lib/os-probes/mounted/90solaris on mounted /dev/sda3
Nov 11 00:09:27 stamina bash[2511]: done
Nov 11 00:09:27 stamina systemd[1]: grub-btrfs.service: Succeeded.
Nov 11 00:09:27 stamina systemd[1]: Finished Regenerate grub-btrfs.cfg.
```

**Comment by Antynea** [comment]
hello,

> Is this supposed to work on non UEFI installations?
I hope this question is not too silly, but I really couldn't find this info anywhere...

Indeed, I don't mention the `UEFI / Bios legacy` compatibility anywhere, because `grub-btrfs` doesn't care about that.
`grub-btrfs` simply adds an additional menu to your existing `Grub` installation, so if `Grub` works on your installation, `grub-btrfs` will work.

However, I have implemented a few limitations:
* If you have explicitly disabled its execution through the config file, it will not run.
```
# Disable grub-btrfs.
# Default: "false"
#GRUB_BTRFS_DISABLE="true"
```
* If the package containing the `btrfs` command isn't installed, it will not run.
[btrfs-progs on Arch Linux](https://archlinux.org/packages/core/x86_64/btrfs-progs)
* If the `grub-mkconfig_lib` file is not found, it will not run.
The file detection does not work correctly on all distros. #180
* If the file system on your root partition isn't btrfs, it will not run.

#
The ouput of `systemctl status grub-btrfs.service` indicates that `grub-btrfs` did not run.
First check the reasons given above.

#
For more complete debugging:
* What is your OS ?
* Can you post the output of `bash -x /etc/grub.d/41_snapshots`
This, will show the line that stops the script.

**Comment by masavini** [comment]
hi,
thanks for your reply.
i reinstalled everything, and now it perfectly works. my bad!

i tried to reinstall everything last night, as well, but i was probably too sleepy... and since i could not find any info about bios grub, i thought it could have been unsupported...

thanks!
