### ISSUE TITLE
Would this work if only /var is on a separate subvolume?

### ISSUE THREAD

**Issue by khang33k** [Antynea/grub-btrfs#204]
I have only /var on a separate subvolume and not /var/log.
Would this still work?

**Comment by Arnie97** [comment]
Sure, the only point here is that `/var/log`, `/var/run` etc. should be writable, otherwise some daemons might fail on startup.

If your system was tweaked for booting from a read-only volume,  or you were booting from a read-write snapshot, then it doesn't matter whether `/var` and its subdirectories were on a separate volume.
