### ISSUE TITLE
Snapper mount missing in systemctl list-units -t mount

### ISSUE THREAD

**Issue by stevensko** [Antynea/grub-btrfs#215]
On endeavourOS I installed snapper-support and then ran the commands to include snapshots in grub. my snapshots apparently aren't mounted in the correct directory because it failed with 

failed to start grub.btrfs.path: Unit /x2esnapshots.mount not found. 

the problem is that there is no snapshots mount for me to replace \x2esnapshots.mount

**Comment by Schievel1** [comment]
Sorry for messing this issue up with my mentions in commits. 
I am working on a daemon right now to watch for snapshots and triggering grub-btrsd instead of relying on systemd mounts and its almost finished. Maybe you want to give it a try. I put instructions into the PR, #218, for more instructions visit https://github.com/Schievel1/grub-btrfs/tree/update-daemon.
