### ISSUE TITLE
Missing information in README file

### ISSUE THREAD

**Issue by bcclsn** [Antynea/grub-btrfs#221]
not an issue but I think 

not a real issue but I think it is better to add information to the README, for all those who install grub-btrfs from source, on fedora or other distros with grub2.

you need to edit /etc/grub.d/41_snapshots-btrfs (from super user) and change row 72 
from: **grub_directory=${GRUB_BTRFS_GRUB_DIRNAME:-"/boot/grub"}** 
to: **grub_directory=${GRUB_BTRFS_GRUB_DIRNAME:-"/boot/grub2"}**

then, you need to edit /etc/default/grub-btrfs and uncomment all rows referred to fedora/grub2 system (/boot/grub2)

regards

**Comment by Schievel1** [comment]
I think you did not do this as intended. The intention is that you don't need to change the file /etc/grub.d/41_snapshots-btrfs since that is overwritten with a new config. 
Instead you change the values in /etc/default/grub-btrfs/config. The `${GRUB_BTRFS_GRUB_DIRNAME:-"/boot/grub"}` means: Use the value in GRUB_BTRFS_GRUB_DIRNAME  unless it's not defined, in this case then use `/boot/grub`
The reason is that 41_snapshots-btrfs can get overwritten with an update, and you would loose your changes where /etc/default/grub-btrfs is usually protected by some mechanism like Gentoos dispatch-conf for example.

To tell Fedora users they have to configure some things it  says
```
# Location of the folder containing the "grub.cfg" file.
# Use by grub-btrfs to save the file "grub-btrfs.cfg".
# Might be grub2 on some systems.
# For example, on Fedora with EFI : "/boot/efi/EFI/fedora"
# Default: "/boot/grub"
#GRUB_BTRFS_GRUB_DIRNAME="/boot/grub2"
```
in /etc/default/grub-btrfs. Maybe it would be better to have another hint for that in the readme.

**Comment by bcclsn** [comment]
well, understood... it is now clearer!

for fedora user, I think it is sufficient to uncomment and edit the config file:

GRUB_BTRFS_GRUB_DIRNAME="/boot/grub2"
GRUB_BTRFS_MKCONFIG=/sbin/grub2-mkconfig
GRUB_BTRFS_SCRIPT_CHECK=grub2-script-check
