### ISSUE TITLE
Grub snapshots menu not working

### ISSUE THREAD

**Issue by alprde** [Antynea/grub-btrfs#268]
Hi, I don't know what happened but when I press enter I get back to main grub menu. I'm using fedora 37.

**Comment by Schievel1** [comment]
This usually happens when the created submenu is either empty or it the file defining the menu doesn't exist. 

I don't know where fedora saves their grub things, a hot guess is /boot/grub2. Can you search somewhere there for the files grub.conf and grub-btrfs.conf and post the contents here and there paths where you found them? 
I guess fedora changed some path or something.

**Comment by alprde** [comment]
yes the grub path was /boot/grub2.
I tried to edit the path while on the grub screen but it didn't work.
normally when updating grub it would update it to /boot/grub2/grub.cfg. Then I accidentally updated it to /boot/efi and the menu is broken. I then installed the nvidia drivers and the system crashed. I got angry too and switched to pop os :)
