### ISSUE TITLE
Does the tool support rollback while booted from a snapshot?

### ISSUE THREAD

**Issue by developer91234** [Antynea/grub-btrfs#310]
I'm on ZFS and too lazy to set up a btrfs system just to check if this works. But I'm wondering how rollback would work given the overlayfs boot method for ro snapshots.

**Comment by Schievel1** [comment]
This tool does no rollbacks. All it does is creating a snapshot list for the grub bootmenu that you can boot into. 
For rollbacks use timeshift or snapper. Those tools on the other hand have the disadvantage, that you have to be able to boot your system in order to boot a different snapshot. This is where grub-btrfs shines.
