### ISSUE TITLE
Feature: Delete snapshots

### ISSUE THREAD

**Issue by hirntot** [Antynea/grub-btrfs#329]
hi there! with timeshift I had the problem twice already that my SSD root folder was completely filled up with snapshots and the system got into trouble (thanks to COW, I guess) and finally crashed. Even when trying to delete snapshots via root command timeshift said, there's no space left, so it can't delete snapshots. Which is ridiculous in a way, but let that be [timeshift's issue](https://github.com/linuxmint/timeshift/issues/221).

**Now my feature Idea for grub-btrfs:**

After reading my intro, it might sound like a workaround... but thinking about it twice, it would feel right to have a "manage snapshots" section at boot, where I could just delete snapshots directly from the btrfs-ssd.

**Comment by Schievel1** [comment]
This is impossible to do because grub does not have proper file system access. This as what an OS is for. But the bootloader is not an OS, it loads the OS. It has rudimentary FS access to load the kernel and the initramfs into RAM.

All grub-btrfs does is adding the option in grub to give the kernel parameters to load different snapshots. At boot time it doesn't know if these snapshots actually exist. It just knows the names and just gives the kernel the name and hopes for the best.
