### ISSUE TITLE
Multiple Subvolumes to snapshot

### ISSUE THREAD

**Issue by euuurgh** [Antynea/grub-btrfs#351]
Hi, first of: great work, this project is really cool.

I am running gentoo, and while I had no trouble installing and setting up grub-btrfs, I do have a setup where the root and home are separate, but still both are backup up via snapper.

My exact btrfs subvolume layout:
```
ID 256 gen 55849 top level 5 path @
ID 257 gen 55854 top level 5 path @home
ID 258 gen 55850 top level 5 path @var
ID 259 gen 55836 top level 5 path @tmp
ID 260 gen 55849 top level 5 path @log
ID 261 gen 55634 top level 5 path @snapshots
ID 262 gen 55794 top level 256 path .snapshots
ID 263 gen 55826 top level 257 path @home/.snapshots
ID 264 gen 55773 top level 262 path .snapshots/1/snapshot
ID 265 gen 55784 top level 263 path @home/.snapshots/1/snapshot
ID 266 gen 55789 top level 262 path .snapshots/2/snapshot
ID 267 gen 55814 top level 263 path @home/.snapshots/2/snapshot
ID 268 gen 55815 top level 263 path @home/.snapshots/3/snapshot
```

I automated updating grub through grub-btrfsd, but don't know how to configure it to back up both the snapshots of home and the root fs, or is this not in the scope of this project? I do have scripts and utilities in my home directory that some of my own system services depend upon. Should I move the location of them to the root fs or is there a other way?

Any and all help would be greatly appreciated. Thanks, and take care

**Comment by Schievel1** [comment]
Hello fellow Gentoo user :)

Grub-btrfs creates a grub menu list with snapshots to boot from. It does not make sense for it to include the home subvolume in there, because grub can not boot them. 
Mind that your @home subvolume is still backed up (if you want to call making snapshots a backup, because it really isn't) it is just not shown in the menu. 

What snapshot is mounted by your kernel is up to your fstab (or other configuration) and I can't really think of a way how grub should influence that.

> I do have scripts and utilities in my home directory that some of my own system services depend upon. Should I move the location of them to the root fs or is there a other way?

I guess so. This is just not a very stable setup if your system can not run because of things in /home missing.
