### ISSUE TITLE
/usr/sbin/grub-mkconfig: 24: /etc/default/grub: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by 74cmonty** [Antynea/grub-btrfs#45]
Hi,
I have an issue after updating grub on Debian 9.2:
thomas@pc8-nb:~$ sudo update-grub
/usr/sbin/grub-mkconfig: 24: /etc/default/grub: Syntax error: "(" unexpected

The relevant line is:
GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("var/lib/docker" "nosnapshot")

Is this Debian specific?

**Comment by Antynea** [comment]
Thanks for your feedback.

Indeed, this is Debian specific ...
my fresh vm install have a same issue.

If you only want to exclude docker, then :
`GRUB_BTRFS_IGNORE_SPECIFIC_PATH="var/lib/docker"` should work

If you want to specify multiple paths to exclude, then that's a problem.

hope to find a solution.

**Comment by Antynea** [comment]
This problem comes from the package `grub-common_2.02~beta3-5`
Newer version available in `testing/sid` repositories corrects it
I tested this package `grub-common_2.02+dfsg1-4_amd64.deb` available in `testing/sid` repositories, and it works just fine.

I can only advise you to upgrade your version if you wish to have the possibility to define several parameters.

**Comment by 74cmonty** [comment]
Can you confirm that the syntax 
GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("var/lib/docker" "nosnapshot")
is not correct, means "nosnapshot" must be deleted?

**Comment by Antynea** [comment]
This syntax is an example that shows how to add multiple paths.
"nosnapshot" doesn't exist on your system, you can delete it.

single parameter:
`GRUB_BTRFS_IGNORE_SPECIFIC_PATH="path/to/ignore"`
multiple parameters:
`GRUB_BTRFS_IGNORE_SPECIFIC_PATH=("first/path/to/ignore" "second/path/to/ignore")`

multiple parameters doesn't work with `grub-common_2.02~beta3-5` package.
