### ISSUE TITLE
Use with manual snapshot

### ISSUE THREAD

**Issue by zarMarco** [Antynea/grub-btrfs#67]
Hi all, can I use this with manual snapshot? I don't use snapper but I create my snapshot with btrfs command. Can I use this for booting my snapshots? If yes, how?

**Comment by Antynea** [comment]
Hello,

> Hi all, can I use this with manual snapshot? I don't use snapper but I create my snapshot with btrfs command.

Yes, snapper is optional.

>  Can I use this for booting my snapshots? If yes, how?

Installed grub-btrfs via "https://github.com/Antynea/grub-btrfs#installation-"

If you want the snapshots populated automatically in GRUB, follow this:
"Https://github.com/Antynea/grub-btrfs#automatically-update-grub"

**Comment by bcclsn** [comment]
hello antynea,

I've the same questions. I've already installed grub-btrfs and auto populated my grub entry, but if I start the last snapshot, I've a lot of error (mostly about systemd network service), so I can't boot successfully into the snapshot.

the snapshot is a perfect copy of the current system: I've snapped the system, reboot the pc and tried to start the snapshot.

**Comment by zarMarco** [comment]
But if I want booted my snapshots, they must be in read and write, or could go in readonly too?

**Comment by Antynea** [comment]
I don't use snapper.
I create my snapshots with the btrfs commands (rw not ro).
I don't have a separate boot partition (for the kernel and systemd to be compatible)
I have no problem, i have no idea about your problems.

Make sure you have no incompatible parameters on `Kernel command line parameters` or `fstab`

Maybe @maximbaz can help you.

**Comment by bcclsn** [comment]
mmm well, we hope @maximbaz will be able to help we.

a few further informations:
- I don't have a separate partition for /boot 
- maybe there is a problem with systemd service startup 
- this is a screen of the errors (the snapshot is a perfect copy o the current system): https://i.postimg.cc/CLjxvqTp/IMG-20190611-162209-244.jpg
ndr.

**Comment by maximbaz** [comment]
Hmmm sorry I don't have any ideas 🤔 I use snapper (which creates ro snapshots), and I dont have a separate partition for /boot either.

**Comment by Kr1ss-XD** [comment]
These bootup messages are looking quite familiar to me, so maybe I can contribute some of my experiences here, especially if my assumption is right that you are booting a readonly snapshot here.

I used to have similar trouble when I was doing so, though I can't recall for sure if the errors I got were about network timesync.
Anyways, what I do remember is that I could get rid of (most of) the errors by telling journald to use temporary storage for the logs rather than trying to save them to the (write protected) root file system.
I did so by setting `storage=volatile` in the systemd `[Journal]` configuration section, inside `/etc/systemd/journald.conf`.

However, what I'm doing now is clearing the snapshots' readonly flag when I want them to be bootable (since I figured it does not make much sense to boot into a r/o filesystem anyways) :
```
# btrfs property set </path/to/snapshot> ro false
```
This works fine for me, and I'm using `storage=persistant` to have the logs in `/var/log/journal` (which btw is a separate subvolume and thus not included in the snapshots).

I would recommend the second method, but both of them should get you going if your issue is the same as I had, i.e. journald trying to store the logs on a write-protected snapshot.

**Comment by bcclsn** [comment]
hi @Kr1ss-XD, thanks for you help.

all my snapshots aren't in ro mode, that's why I don't know why I can't boot into the snapshot. 
anyway, I get the snapshot with this script https://github.com/bcclsn/xiaomi-mi-air/blob/master/.script/btrfs_snap.sh

having said that, I set the taken snapshot in ro false and edit also the journald.conf but without any success.

**Comment by pal-pinter** [comment]
Hi @bcclsn 

I've received the same error on Archlinux. The problem was with the /var directory. If you make a @var subvolume mounted the /var directory, you can boot into the new snapshot. (Temp solution to probe it, delete content of the /var directory in the snapshot. However the first boot was very slow in this case)

**Comment by bcclsn** [comment]
hi @pal-pinter 

thank you so much! deleting the /var directory from the snapshot-X, I was able to start it correctly. 
the system autocreate three new snapshot in /path/snapshot-X/var/lib/portables ~/var/lib/machines and ~/var/tmp, but I think it is necessary.

ndr. anyway, I have already the @var subvolume, so I must try the other solution

**Comment by librewish** [comment]
I'm also getting many errors when trying to boot into a snapshot using grub 
So I am using snapper snap-pac snap-pac-grub grub-btrfs

**Comment by librewish** [comment]
Okay what I did was to remove snapper install time shifts auto snap
Now I can boot into snapshots.
So it seems its snapper problem

**Comment by viogq** [comment]
same here! snapper is 100% breakware except on SUSE. timeshift much better! this project **grub-btrfs** works with timeshift nicely. But: grub-btrfs needs the wiki active! many people come here because of a broken  Linux, and what they want to know is how to manually boot into a snapshop . they want the actually working grub lines so they can do it 100% manual since all wikis and automatisms just always set you up for failure.

Only manual work will ever succeed.  so where are the manual cheatcodes? BTW: I was able to rescue my system with a manual grub line after snapping the RO snap into a RW snap  into the topmost dir  and called it  "newRootHereNow"

**Comment by Antynea** [comment]
Continued discussion #92
