### ISSUE TITLE
Automatically create r/w snapshot when selecting r/o

### ISSUE THREAD

**Issue by darkdragon-001** [Antynea/grub-btrfs#88]
When one is selecting a r/o snapshot, `grub-btrfs` should create a new snapshot based on the selection one but in r/w mode such that the original snapshot is not changed!

**Comment by maximbaz** [comment]
I don't think it's possible (we don't execute any scripts when you select an entry in grub), but more importantly I think creating new snapshots is out of scope for this project. Consider creating `r/w` snapshots instead of `r/o`, maybe?

**Comment by darkdragon-001** [comment]
@maximbaz They are r/o for a reason: Booting into a snapshot _changes_ the data and might just destroy the last available backup. Sometimes, one needs several tries until one achieves to fix a problem, so there should be an option to start over.

I can understand that there might be no easy solution but would be more than welcome if anyone has an idea how to achieve this.

**Comment by maximbaz** [comment]
Of course! For recovery purposes I think what people usually do is they boot in the r/o snapshot, and then either mount the "broken" root and make changes manually (if you know what change broke it and it's easy to revert by hand), or they make a r/w snapshot manually by hand from a certain specific point, and then boot into that.

**Comment by darkdragon-001** [comment]
The problem is, I can't boot an r/o snapshot... Some parts of the fs need to be writable. Of course one could create many different subvolumes and figure out which folders need to be writable, but I prefer to have everything in one subvolume to make backups easier and keep consistency between folders.

**Comment by maximbaz** [comment]
Oh, I see, it was never a problem for me to boot into a r/o snapshot 🤔 

Let's brainstorm what are the possible options to solve the problem for you.

I would definitely investigate why you can't boot, for me even GUI loads just fine, so if you could reliably get at least into tty then you could start from taking a second snapshot before trying to fix a problem...

To the best of my knowledge we can't execute scripts in grub, so other ideas could be about doing something at the same time of taking snapshots, or very early after boot, before things start to fail for you due to r/o system.

One stupid but simple approach could be to take... 5 r/w snapshots instead of one, to have 5 attempts to fix the problem 😐 

If you can find a way to run some script very early after boot, maybe you can make a script that on boot takes a snapshot of the currently booted root subvolume?

What do you think, and do you have any other ideas?

**Comment by darkdragon-001** [comment]
Best would be if grub had scripting support to run scripts _before_ the kernel is executed.

There is also the possibility to chain-boot another kernel before just for the snapshot and then kexec to the other one. Probably this is just overkill.

Apart from this, I don't have enough knowledge which options exist to run scripts within the boot process as early as possible...

I guess for now, I will stick with having one r/w snapshot lying around which I will boot into for a shell in order to manually create r/w copies of the snapshot I want to test...

Hopefully, I get a coreboot laptop soon, so I can just build something myself and dump grub completely.

**Comment by maximbaz** [comment]
@darkdragon-001 FYI someone found a solution for booting on readonly snapshots, turns out `/var/log` must be on a separate subvolume otherwise journald is unable to write anything and prevents boot. See #92 for the discussion.
