### ISSUE TITLE
Feature Request: enable password protection for snapshots/snapshot submenu

### ISSUE THREAD

**Issue by nephros** [Antynea/grub-btrfs#95]
Grub2 supports superuser and user access using passwords.

As snapshots are clearly the domain of a sysadmin and not a regular user, any entries allowing to boot from a snapshot should be (optionally, or even by default) protected by such passwords.

TL;DR this can be done by adding `--user ""` to the `menuentry` line, but there would need to be some plumbing in the config file and documentation to make it configurable.

https://help.ubuntu.com/community/Grub2/Passwords
https://www.gnu.org/software/grub/manual/grub/grub.html#Authentication-and-authorisation

TODOs:

- [ ] Enable password protection for submenu
- [ ] Enable password protection for menuentry
- [ ] Enable enabling/disabling in config file
- [ ] Enable specifying specific user(s) in the config file ( `--users ""` vs `--users "user1, user2"`)
- [ ] Update documentation

**Comment by Antynea** [comment]
When the grub password protection is activated by the user, it is active for all submenus and menuentries present in `grub.cfg`.
It turns out that it isn't possible to activate protection only for a specific sub-menu or menuentry.

When protection is active, you must use `--unrestricted` to disable it in a submenu or menuentry.
By default, `superusers` has full access, so it isn't necessary to specify `--user ""`

When a submenu is unlocked by an authorized user, all menuentries that are part of the submenu are also unlocked.
It is therefore not possible to use a different user between the submenu and the menuentries.

therefore, password protection support is only applied to the submenu. grub2 doesn't allow fine-tuning the security.

the PR offers the possibility to disable the protection of the submenu of grub-btrfs via `--unrestricted`
or to specify authorized users via `--users foo, bar`

To do this,
in the configuration file:
uncomment and specify the authorized user(s)
`# GRUB_BTRFS_PROTECTION_AUTHORIZED_USERS = "foo,bar"`
or
allow everyone
`GRUB_BTRFS_DISABLE_PROTECTION_SUBMENU = "true"`

It is up to the user to enable password protection, grub-btrfs will not. (because it is a general protection and not specific).
for example add :
```
set superusers="root"
password_pbkdf2 root grub.pbkdf2.sha512.10000.biglongstring
password user1 insecure
```
in `/etc/grub.d/40_custom`
refer to the [Grub documentation](https://www.gnu.org/software/grub/manual/grub/grub.html#Authentication-and-authorisation)

**Comment by Antynea** [comment]
Merge to master branch.
If you have any suggestions/questions, re-open this issue.
